# Generated by Django 4.1.3 on 2022-11-10 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
                ('shorts', models.SlugField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=30)),
                ('faculty_name', models.CharField(max_length=30)),
                ('faculty_id', models.CharField(max_length=15)),
                ('shorts', models.SlugField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=10)),
                ('mat_number', models.CharField(max_length=20)),
                ('admission_id', models.CharField(max_length=15)),
                ('nationality', models.CharField(max_length=40)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('dob', models.CharField(max_length=100)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.department')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.faculty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100)),
                ('staff_type', models.CharField(choices=[('Senior_Professor', 'Senior_Professor'), ('Professor', 'Professor'), ('Lecturer_1', 'Lecturer_1'), ('Lecturer_2', 'Lecturer_2'), ('Lecturer_3', 'Lecturer_3'), ('Junior_Lecturer', 'Junior_Lecturer'), ('Graduate_assistant', 'Graduate_assistant')], max_length=20)),
                ('staff_app_num', models.CharField(max_length=15)),
                ('status', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.department')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.faculty'),
        ),
    ]
