# Generated by Django 4.1.3 on 2022-11-26 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='faculty_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='admission_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sex',
        ),
    ]
