# Generated by Django 4.1.3 on 2022-11-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_alter_studentsubmission_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='graded',
            field=models.BooleanField(default=False),
        ),
    ]
